### ISSUE TITLE
Не выгружаются категории

### ISSUE THREAD

**Issue by evgrezanov** [evgrezanov/bonus-plus-wp#28]

**Comment by Mikuznetsov** [comment]
Для категорий первого уровня не должен передаваться "pid"
ID категорий и товаров не должны совпадать. Было совпадение у 2х товаров и категорий  - "id"
Параметр "а" не добавил, без него все ок.

**Comment by evgrezanov** [comment]
>Для категорий первого уровня не должен передаваться "pid"
>ID категорий и товаров не должны совпадать. Было совпадение у 2х товаров и категорий - "id"

так себе, есть идеи как это решить? иначе получается у многих может проблема возникнуть

@Mikuznetsov

**Comment by Mikuznetsov** [comment]
Это решил проверкой перед добавлением категорий в массив. Если pid =0, то в json этой строки не будет и экспорт отлично работает
