### ISSUE TITLE
Списание бонусов

### ISSUE THREAD

**Issue by evgrezanov** [evgrezanov/bonus-plus-wp#40]
# todo

1. Сделать несколько акций с различными схемами начисления-списания бонусов (начисление, списание, процент) 
2. Переписать функцию вывода информации о бонусах на странице **корзины и чекаута** и карточке товара:
2.1 Ваш бонусный баланс NN.NN бонусов
2.2 За покупку будет списано NN.NN бонусов / На данную покупку бонусы не применяются
2.3 После покупки будет начислено NN.NN бонусов
3. Списание бонусов после того как заказ Выполнен, когда заказ в статусе ожидает оплата - бонусы нужно резервировать https://bonusplus.pro/api/Help/Api/PATCH-customer-phoneNumber-balance-reserve
4. Списываем все доступные для списания бонусы

https://user-images.githubusercontent.com/5329288/230711843-d8e4dbbe-4960-4712-8668-569e987596b7.mp4

## User story

Пример интеграции 1с Битрикс и БонусПлюс
 https://hookah-time.shop/
https://bonaladies.ru/

>Как я для себя это вижу клиент заходит в карточку видит что при покупке данного товара ему начислится такой-то бонус. 
Далее клиент помещают товар в корзину в корзине чуть ниже поля купоны написана сумма для списания 
Клиент нажимает кнопку списать ему приходит смс с кодом и подтверждает путём вода 
<Наверное это надо через купоны саму скидку реализовать>
Но допустим на некоторые товары мы можем применить ограничения для списания, допустим не 25 % а 15% но не более чем баланс бонусов 
В этом случае мы должны отправит в б+ список товаров и узнать размер скидки и выпустить купон на сумму скидки

>Сценариев множество
Во-первых мы передаем товары в бонус плюс с сайта соответственно бонус плюс знает id наших товаров
Нам надо только сообщить что в корзине и б+ скажет какая сумма скидки 
Тоесть настройки скидки на категории это в Нутри Б+ и нашу задачу не задевает

>Нам надо научится делать купон из полученного результата 
Тесть мы говорим id товаров 
Бонус плюс передаёт сумму скидки допустим 100 р 
Мы должны вставить эту сумму в купоны например

>Вопрос только как создать купон и вставить его в поле купоны чтобы клиент не додумывал а видел только результат

>там 2 сценария если клиент не авторизован то после оформления заказа отображается информация о начислениях

>2й СЦЕНАРИ ОТОБРОЖАЕТ СКОЛЬКО БУДЕТ СПИСАНО ЕСЛИ ДОСТУПНО! "ТОЕСТЬ  НЕТ КНОПКИ СПИСАТЬ" И СКОЛЬКО БУДЕТ НАЧИСЛЕНО ПОСЛЕ ПОКУПКИ

**Comment by Mikuznetsov** [comment]
1. Сделать несколько акций с различными схемами начисления-списания бонусов (начисление, списание, процент) 
0,5ч
2. Переписать функцию вывода информации о бонусах на странице **корзины и чекаута** и карточке товара:
2.1 Ваш бонусный баланс NN.NN бонусов
2ч
2.2 За покупку будет списано NN.NN бонусов / На данную покупку бонусы не применяются
2ч
2.3 После покупки будет начислено NN.NN бонусов
1ч
3. Списание бонусов после того как заказ Выполнен, когда заказ в статусе ожидает оплата - бонусы нужно резервировать https://bonusplus.pro/api/Help/Api/PATCH-customer-phoneNumber-balance-reserve
3ч
4. Списываем все доступные для списания бонусы
1ч

**Comment by evgrezanov** [comment]
@Mikuznetsov в корзину можно так примерно

```
// Создаем функцию для вывода дополнительных строк
function additional_cart_item_data( $cart_item, $cart_item_key ) {
    // Ваш код для получения данных или логики для отображения дополнительной информации
    $additional_data = 'Дополнительная информация'; // Замените эту строку своим кодом

    echo '<tr>';
    echo '<td colspan="2">' . $additional_data . '</td>';
    echo '</tr>';
}

// Добавляем хук для вывода дополнительных строк в таблице товаров корзины
add_action( 'woocommerce_after_cart_item_name', 'additional_cart_item_data', 10, 2 );
```

**Comment by Mikuznetsov** [comment]
Нашел такое решение, добавляем fee в объект WC()->cart - это пока заказа нет. Происходит пересчет
Хотел написать красиво, чтобы подставлять переменную, но со статическими функциями не получается.
1. Получить переменную из запроса, записать ее в переменную, которую видно во всем классе
2. Подставить типа $this->max_debit_bonuses

add_action('woocommerce_cart_calculate_fees', [__CLASS__, 'add_custom_fee_on_checkout']);
    public static function add_custom_fee_on_checkout()
    {
        $fee_name = 'Списание бонусов';
        $fee_amount = -210.00; // Тут поставить переменную, которую получаем из запроса
        $taxable = true;
        $tax_class = 'bpwp-bonuses-reserved';
        
        WC()->cart->add_fee($fee_name, $fee_amount, $taxable, $tax_class);
    }

**Comment by evgrezanov** [comment]
![image](https://github.com/evgrezanov/bonus-plus-wp/assets/5329288/41b23142-fb8a-4a97-84c4-4dc2d4cd512f)
@Mikuznetsov тут пишет пользователь что 2 раза списываются бонусы в заказе - надо пофиксить
