### ISSUE TITLE
Неверный вывод в ЛК если пользователь существует в Б+

### ISSUE THREAD

**Issue by yurovigorr** [evgrezanov/bonus-plus-wp#42]
# User story
В Мой Аккаунт - Бонус+ выводится "Вы еще не зарегистрированы в программе лояльности" с кнопкой "Создать учетную запись" (хотя в действительности аккаунт с данным номером есть в Бонус+). При нажатии на предложенную кнопку выходит "При регистрации произошла ошибка
{"code":"CUSTOMER_ALREADY_EXISTS","msg":"Пользователь с заданным номером телефона или номером карты уже существует."}"
Есть ли какой-то хотфикс?

**Comment by evgrezanov** [comment]
@yurovigorr Добрый день!
Поправим в следующем релизе

**Comment by evgrezanov** [comment]
@yurovigorr в настоящий момент функция привязки существующего клиента из б+ на сайт до конца не реализована - там может быть несколько сценариев

чтобы исправить проблему:
 - введите в Платежном адресе телефон который указан у клиента в б+ и сохраните платежный адрес
 - разлогинтесь на сайте 
 - заново авторизуйтесь на сайте
 - при авторизации данные подтянутся

**Comment by evgrezanov** [comment]
@Mikuznetsov 
## TO DO
Линковка существующего в Б+ клиента с пользователем сайта

- [ ] при входе в ЛК/Бонус + проверяем телефон и мету б+
- [ ] если нет телефона ->сообщение с просьбой сохранить телефон
- [ ] если нет меты-> делаем запрос к б+, с проверкой есть ли пользователь с таким телефоном -> сообщение о необходимости продтвердить телефон через СМС -Ю либо выкачиваем мету, либо регистрируем нового
