### ISSUE TITLE
Не происходит выгрузка товара в БП

### ISSUE THREAD

**Issue by yurovigorr** [evgrezanov/bonus-plus-wp#50]
В версии 2.4 работало, в версии 2.6 сломалось (2.5 не тестил). 
В версии 2.6 при нажатии на кнопку экспорта самого экспорта не происходит, идет перенаправление на страницу настроек плагина.
Upd: В версии 2.4 указано, что экспортированы категории, товары и вариации, но фактически в БП список товаров пуст.
Upd2: установил опять версию 2.6, экспорт не заработал, товары не появились, но сумма баллов к списанию и начислению при оформлении заказа появились (ранее сами цифры отсутствовали). Было указано: К списанию 550, к начислению 475. По факту начислилось на 150 баллов больше, так как есть логика акции, согласно которой при чеке от 5к идет начисление доп 150 баллов. Это бы хотелось чтобы отображалось тоже.

**Comment by evgrezanov** [comment]
@yurovigorr выложил дев версию - там поправлено проверяйте https://github.com/evgrezanov/bonus-plus-wp/releases/tag/v2.7
в офф репозитории обновлю на неделю

**Comment by yurovigorr** [comment]
Теперь это "На сайте возникла критическая ошибка. Пожалуйста, проверьте входящие сообщения почты администратора для дальнейших инструкций.

[Узнайте больше про решение проблем с WordPress.](https://wordpress.org/documentation/article/faq-troubleshooting/)"

**Comment by evgrezanov** [comment]
@yurovigorr есть текст ошибки из debug.log? 
Выгрузил в офф репозиторий - попробуйте обновится оттуда, также обновил требования к окружению, версию РНР

**Comment by yurovigorr** [comment]
@evgrezanov ошибка была в недостатке памяти, увеличил значение PHP директивы memory_limit, все стало норм. Благодарю.
P.S. Панируется ли выводить реальное количество баллов к начислению (+150 как указал выше)? Еще было бы круто выводить текст акции, по которой идет доп начисление.

**Comment by yurovigorr** [comment]
Понял, в чем конкретно баг с бонусами: судя по всему, у вас идет расчет бонусов к начислению по сумме до списания баллов, а у нас Б+ считает баллы к начислению по сумме оплаты итоговой после списания баллов за покупку. Пример: Имеем в корзине 2 товара по 2500р. В карточке этого товара отображается к начислению 225 баллов за шт (считает, по идее, так: 5% (это 125 баллов) за покупку + 100 баллов за чек выше 2к). 

_Стоит отметить: у нас по карте начисление 5% и акции +100 бонусов при чеке от 2к, +150 при чеке от 3.5к, +250 при чеке от 5к._ 
Идем далее:
В корзине отображается, что к начислению 450 баллов (хотя корзина уже на 5к, итого к начислению должно быть 125+125+250=500 баллов), а к списанию 500 баллов. Но, так как мы оплачиваем в таком случае 4500 руб, то к начислению выходит 125+125+150 = 400 баллов. Так БонусПлюс на своей стороне и рассчитывает и проводит, а вот в плагине происходит не так...

**Comment by evgrezanov** [comment]
> Понял, в чем конкретно баг с бонусами: судя по всему, у вас идет расчет бонусов к начислению по сумме до списания баллов, а у нас Б+ считает баллы к начислению по сумме оплаты итоговой после списания баллов за покупку. Пример: Имеем в корзине 2 товара по 2500р. В карточке этого товара отображается к начислению 225 баллов за шт (считает, по идее, так: 5% (это 125 баллов) за покупку + 100 баллов за чек выше 2к).
> 
> _Стоит отметить: у нас по карте начисление 5% и акции +100 бонусов при чеке от 2к, +150 при чеке от 3.5к, +200 при чеке от 5к._ Идем далее: В корзине отображается, что к начислению 450 баллов (считает 125+125+200=450 баллов), а к списанию 500 баллов. Но, так как мы оплачиваем в таком случае 4500 руб, то к начислению выходит 112,5+112,5 (это за товары суммой 4500) + 200 (так как акция считает сумму чека, а не оплаты после скидки) = 425 баллов. Так БонусПлюс на своей стороне и рассчитывает и проводит, а вот в плагине происходит не так...

можете дать ссылку на товар? попробуем повторить - пока сложно понять

**Comment by evgrezanov** [comment]
> Понял, в чем конкретно баг с бонусами: судя по всему, у вас идет расчет бонусов к начислению по сумме до списания баллов, а у нас Б+ считает баллы к начислению по сумме оплаты итоговой после списания баллов за покупку. Пример: Имеем в корзине 2 товара по 2500р. В карточке этого товара отображается к начислению 225 баллов за шт (считает, по идее, так: 5% (это 125 баллов) за покупку + 100 баллов за чек выше 2к).
> 
> _Стоит отметить: у нас по карте начисление 5% и акции +100 бонусов при чеке от 2к, +150 при чеке от 3.5к, +200 при чеке от 5к._ Идем далее: В корзине отображается, что к начислению 450 баллов (считает 125+125+200=450 баллов), а к списанию 500 баллов. Но, так как мы оплачиваем в таком случае 4500 руб, то к начислению выходит 112,5+112,5 (это за товары суммой 4500) + 200 (так как акция считает сумму чека, а не оплаты после скидки) = 425 баллов. Так БонусПлюс на своей стороне и рассчитывает и проводит, а вот в плагине происходит не так...

в отдельной задаче будем смотреть https://github.com/evgrezanov/bonus-plus-wp/issues/52
