### ISSUE TITLE
Версия 2.11 Баги

### ISSUE THREAD

**Issue by yurovigorr** [evgrezanov/bonus-plus-wp#70]
Когда введен в платежный адрес существующий в базе БП номер телефона - вечная загрузка карты.
![2024-04-19_16-47-38](https://github.com/evgrezanov/bonus-plus-wp/assets/75913596/570e5828-0e9c-46d4-bb8e-3f4dba6c30e4)
Когда введен несуществующий - просто вечная загрузка, нет никакого текста, ошибок тоже.

Клиент попытался совершить покупку, ввел код из смс, но баллы не списались и не начислились, в ЛК БП пусто по данному заказу. 
Возможно, вам будет удобно созвониться?
Есть ли стабильная версия?

**Comment by evgrezanov** [comment]
@yurovigorr сегодня тестируем новую версию, можем созвонится или напишите в телегу @redmonkey73 - договоримся по времени

**Comment by evgrezanov** [comment]
@yurovigorr обновили версию плагина - попробуйте теперь
