### ISSUE TITLE
Не работает плагин с версией PHP 7.4

### ISSUE THREAD

**Issue by olgatrick** [evgrezanov/bonus-plus-wp#73]
К сожалению нет технической возможности в данный момент обновить версию PHP выше чем 7.4 (при версиях выше выдает критическую ошибку на сайте)
Подскажите, пожалуйста, есть ли какая то возможность получить версию плагина совместимого с версией 7.4?
В данный момент все работает криво и косо, требует дату рождения в платежном адресе и тд. Очень долгий пути клиента никто ничего не понимает при оформлении заказа.
Очень нужна помощь

**Comment by evgrezanov** [comment]
@olgatrick напишите в телеграмм @redmonkey73 или на почту evgrezanov@gmail.com
